Search.appendIndex(
    [
                {
            "fqsen": "\\Database\\MyPdo",
            "name": "MyPdo",
            "summary": "Classe\u0020permettant\u0020de\u0020retourner\u0020une\u0020instance\u0020unique\u0020et\u0020configur\u00E9e\u0020de\u0020PDO.",
            "url": "classes/Database-MyPdo.html"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020priv\u00E9.",
            "url": "classes/Database-MyPdo.html#method___construct"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "Emp\u00EAcher\u0020le\u0020clonage,\u0020le\u0020singleton\u0020doit\u0020rester\u0020unique.",
            "url": "classes/Database-MyPdo.html#method___clone"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "Point\u0020d\u0027acc\u00E8s\u0020\u00E0\u0020l\u0027instance\u0020unique.",
            "url": "classes/Database-MyPdo.html#method_getInstance"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AsetConfiguration\u0028\u0029",
            "name": "setConfiguration",
            "summary": "Fixer\u0020programmatiquement\u0020la\u0020configuration\u0020de\u0020la\u0020connexion\u0020\u00E0\u0020la\u0020BD.",
            "url": "classes/Database-MyPdo.html#method_setConfiguration"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AhasConfiguration\u0028\u0029",
            "name": "hasConfiguration",
            "summary": "V\u00E9rifier\u0020si\u0020la\u0020configuration\u0020de\u0020la\u0020connexion\u0020\u00E0\u0020la\u0020BD\u0020a\u0020\u00E9t\u00E9\u0020effectu\u00E9e.",
            "url": "classes/Database-MyPdo.html#method_hasConfiguration"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AsetConfigurationFromEnvironmentVariables\u0028\u0029",
            "name": "setConfigurationFromEnvironmentVariables",
            "summary": "Lire\u0020la\u0020configuration\u0020depuis\u0020des\u0020variables\u0020d\u0027environnement.",
            "url": "classes/Database-MyPdo.html#method_setConfigurationFromEnvironmentVariables"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AsetConfigurationFromIniFile\u0028\u0029",
            "name": "setConfigurationFromIniFile",
            "summary": "Lire\u0020la\u0020configuration\u0020depuis\u0020un\u0020fichier\u0020ini.",
            "url": "classes/Database-MyPdo.html#method_setConfigurationFromIniFile"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A\u0024myPdoInstance",
            "name": "myPdoInstance",
            "summary": "Instance\u0020unique\u0020de\u0020PDO.",
            "url": "classes/Database-MyPdo.html#property_myPdoInstance"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A\u0024dsn",
            "name": "dsn",
            "summary": "DSN\u0020pour\u0020la\u0020connexion\u0020BD.",
            "url": "classes/Database-MyPdo.html#property_dsn"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A\u0024username",
            "name": "username",
            "summary": "Nom\u0020d\u0027utilisateur\u0020pour\u0020la\u0020connexion\u0020BD.",
            "url": "classes/Database-MyPdo.html#property_username"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A\u0024password",
            "name": "password",
            "summary": "Mot\u0020de\u0020passe\u0020pour\u0020la\u0020connexion\u0020BD.",
            "url": "classes/Database-MyPdo.html#property_password"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003A\u0024options",
            "name": "options",
            "summary": "Options\u0020du\u0020pilote\u0020BD.",
            "url": "classes/Database-MyPdo.html#property_options"
        },                {
            "fqsen": "\\Entity\\Collection\\EpisodeCollection",
            "name": "EpisodeCollection",
            "summary": "",
            "url": "classes/Entity-Collection-EpisodeCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\EpisodeCollection\u003A\u003AfindBySeasonId\u0028\u0029",
            "name": "findBySeasonId",
            "summary": "Permets\u0020de\u0020trouver\u0020les\u0020\u00E9pisodes\u0020de\u0020la\u0020saison\u0020d\u0027une\u0020s\u00E9rie\u0020en\u0020fonction\u0020de\u0020l\u0027identifiant\u0020de\u0020cette\u0020s\u00E9rie",
            "url": "classes/Entity-Collection-EpisodeCollection.html#method_findBySeasonId"
        },                {
            "fqsen": "\\Entity\\Collection\\GenreCollection",
            "name": "GenreCollection",
            "summary": "",
            "url": "classes/Entity-Collection-GenreCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\GenreCollection\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Permet\u0020de\u0020retrouver\u0020tout\u0020les\u0020genres",
            "url": "classes/Entity-Collection-GenreCollection.html#method_findAll"
        },                {
            "fqsen": "\\Entity\\Collection\\GenreCollection\u003A\u003AfindByTVShowId\u0028\u0029",
            "name": "findByTVShowId",
            "summary": "Retoruve\u0020la\u0020liste\u0020des\u0020genres\u0020selon\u0020l\u0027identifiant\u0020d\u0027une\u0020s\u00E9rie",
            "url": "classes/Entity-Collection-GenreCollection.html#method_findByTVShowId"
        },                {
            "fqsen": "\\Entity\\Collection\\SeasonCollection",
            "name": "SeasonCollection",
            "summary": "",
            "url": "classes/Entity-Collection-SeasonCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\SeasonCollection\u003A\u003AfindByTVShowId\u0028\u0029",
            "name": "findByTVShowId",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020les\u0020saisons\u0020d\u0027une\u0020s\u00E9rie",
            "url": "classes/Entity-Collection-SeasonCollection.html#method_findByTVShowId"
        },                {
            "fqsen": "\\Entity\\Collection\\TVShowCollection",
            "name": "TVShowCollection",
            "summary": "",
            "url": "classes/Entity-Collection-TVShowCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\TVShowCollection\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020tout\u0020les\u0020s\u00E9rie",
            "url": "classes/Entity-Collection-TVShowCollection.html#method_findAll"
        },                {
            "fqsen": "\\Entity\\Collection\\TVShowCollection\u003A\u003AfindByGenreId\u0028\u0029",
            "name": "findByGenreId",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020les\u0020s\u00E9rie\u0020selon\u0020leur\u0020genre",
            "url": "classes/Entity-Collection-TVShowCollection.html#method_findByGenreId"
        },                {
            "fqsen": "\\Entity\\Collection\\TVShowCollection\u003A\u003AfindTVShowByResearch\u0028\u0029",
            "name": "findTVShowByResearch",
            "summary": "Permet\u0020de\u0020retrouver\u0020les\u0020s\u00E9rie\u0020selon\u0020des\u0020mots",
            "url": "classes/Entity-Collection-TVShowCollection.html#method_findTVShowByResearch"
        },                {
            "fqsen": "\\Entity\\Episode",
            "name": "Episode",
            "summary": "",
            "url": "classes/Entity-Episode.html"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_setId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetSeasonId\u0028\u0029",
            "name": "getSeasonId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getSeasonId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AsetSeasonId\u0028\u0029",
            "name": "setSeasonId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_setSeasonId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetEpisodeNumber\u0028\u0029",
            "name": "getEpisodeNumber",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getEpisodeNumber"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AsetEpisodeNumber\u0028\u0029",
            "name": "setEpisodeNumber",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_setEpisodeNumber"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetOverview\u0028\u0029",
            "name": "getOverview",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getOverview"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AsetOverview\u0028\u0029",
            "name": "setOverview",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_setOverview"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_setName"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Entity-Episode.html#property_id"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003A\u0024seasonId",
            "name": "seasonId",
            "summary": "",
            "url": "classes/Entity-Episode.html#property_seasonId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Entity-Episode.html#property_name"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003A\u0024overview",
            "name": "overview",
            "summary": "",
            "url": "classes/Entity-Episode.html#property_overview"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003A\u0024episodeNumber",
            "name": "episodeNumber",
            "summary": "",
            "url": "classes/Entity-Episode.html#property_episodeNumber"
        },                {
            "fqsen": "\\Entity\\Exception\\EntityNotFoundException",
            "name": "EntityNotFoundException",
            "summary": "",
            "url": "classes/Entity-Exception-EntityNotFoundException.html"
        },                {
            "fqsen": "\\Entity\\Exception\\ParameterException",
            "name": "ParameterException",
            "summary": "",
            "url": "classes/Entity-Exception-ParameterException.html"
        },                {
            "fqsen": "\\Entity\\Genre",
            "name": "Genre",
            "summary": "",
            "url": "classes/Entity-Genre.html"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Genre.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Genre.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Permet\u0020de\u0020trouver\u0020un\u0020genre\u0020en\u0020fonction\u0020de\u0020son\u0020\u0020identifiant",
            "url": "classes/Entity-Genre.html#method_findById"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Entity-Genre.html#property_id"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Entity-Genre.html#property_name"
        },                {
            "fqsen": "\\Entity\\Poster",
            "name": "Poster",
            "summary": "",
            "url": "classes/Entity-Poster.html"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_setId"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AsetJpeg\u0028\u0029",
            "name": "setJpeg",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_setJpeg"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AgetJpeg\u0028\u0029",
            "name": "getJpeg",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_getJpeg"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "M\u00E9thode\u0020de\u0020classe\u0020qui\u0020renvoie\u0020et\u0020cr\u00E9e\u0020une\u0020instance\u0020d\u0027un\u0020Poster\u0020avec\u0020son\u0020id\u0020et\u0020son\u0020jpeg",
            "url": "classes/Entity-Poster.html#method_findById"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Entity-Poster.html#property_id"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003A\u0024jpeg",
            "name": "jpeg",
            "summary": "",
            "url": "classes/Entity-Poster.html#property_jpeg"
        },                {
            "fqsen": "\\Entity\\Season",
            "name": "Season",
            "summary": "",
            "url": "classes/Entity-Season.html"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_setId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AsetTvShowId\u0028\u0029",
            "name": "setTvShowId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_setTvShowId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Entity-Season.html#method_setName"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AsetSeasonNumber\u0028\u0029",
            "name": "setSeasonNumber",
            "summary": "",
            "url": "classes/Entity-Season.html#method_setSeasonNumber"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AsetPosterId\u0028\u0029",
            "name": "setPosterId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_setPosterId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetTvShowId\u0028\u0029",
            "name": "getTvShowId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getTvShowId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetSeasonNumber\u0028\u0029",
            "name": "getSeasonNumber",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getSeasonNumber"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetPosterId\u0028\u0029",
            "name": "getPosterId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getPosterId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020une\u0020saison\u0020en\u0020fonction\u0020de\u0020son\u0020identifiant",
            "url": "classes/Entity-Season.html#method_findById"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Entity-Season.html#property_id"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003A\u0024tvShowId",
            "name": "tvShowId",
            "summary": "",
            "url": "classes/Entity-Season.html#property_tvShowId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Entity-Season.html#property_name"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003A\u0024seasonNumber",
            "name": "seasonNumber",
            "summary": "",
            "url": "classes/Entity-Season.html#property_seasonNumber"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003A\u0024posterId",
            "name": "posterId",
            "summary": "",
            "url": "classes/Entity-Season.html#property_posterId"
        },                {
            "fqsen": "\\Entity\\TVShow",
            "name": "TVShow",
            "summary": "",
            "url": "classes/Entity-TVShow.html"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method___construct"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getId"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getName"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetOriginalName\u0028\u0029",
            "name": "getOriginalName",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getOriginalName"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetHomepage\u0028\u0029",
            "name": "getHomepage",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getHomepage"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetOverview\u0028\u0029",
            "name": "getOverview",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getOverview"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AgetPosterId\u0028\u0029",
            "name": "getPosterId",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_getPosterId"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setId"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setName"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetOriginalName\u0028\u0029",
            "name": "setOriginalName",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setOriginalName"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetHomepage\u0028\u0029",
            "name": "setHomepage",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setHomepage"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetOverview\u0028\u0029",
            "name": "setOverview",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setOverview"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AsetPosterId\u0028\u0029",
            "name": "setPosterId",
            "summary": "",
            "url": "classes/Entity-TVShow.html#method_setPosterId"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Permet\u0020de\u0020trouver\u0020une\u0020s\u00E9rie\u0020en\u0020fonction\u0020de\u0020son\u0020identifiant",
            "url": "classes/Entity-TVShow.html#method_findById"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003AfindPosterById\u0028\u0029",
            "name": "findPosterById",
            "summary": "Renvoie\u0020l\u0027instance\u0020de\u0020Poster\u0020appartenant\u0020\u00E0\u0020l\u0027id\u0020de\u0020la\u0020classe\u0020TVShow",
            "url": "classes/Entity-TVShow.html#method_findPosterById"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Permet\u0020de\u0020supprimer\u0020une\u0020s\u00E9rie",
            "url": "classes/Entity-TVShow.html#method_delete"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Permet\u0020de\u0020mettre\u0020\u00E0\u0020jour\u0020une\u0020s\u00E9rie",
            "url": "classes/Entity-TVShow.html#method_update"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "Permet\u0020d\u0027ins\u00E9rer\u0020une\u0020s\u00E9rie",
            "url": "classes/Entity-TVShow.html#method_insert"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Permet\u0020d\u0027ins\u00E9rer\u0020ou\u0020supprimer\u0020une\u0020s\u00E9rie\u0020en\u0020fonction\u0020de\u0020son\u0020existence\u0020ou\u0020non",
            "url": "classes/Entity-TVShow.html#method_save"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Permet\u0020de\u0020cr\u00E9er\u0020une\u0020s\u00E9rie",
            "url": "classes/Entity-TVShow.html#method_create"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_id"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_name"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024originalName",
            "name": "originalName",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_originalName"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024homepage",
            "name": "homepage",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_homepage"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024overview",
            "name": "overview",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_overview"
        },                {
            "fqsen": "\\Entity\\TVShow\u003A\u003A\u0024posterId",
            "name": "posterId",
            "summary": "",
            "url": "classes/Entity-TVShow.html#property_posterId"
        },                {
            "fqsen": "\\Html\\AppWebPage",
            "name": "AppWebPage",
            "summary": "",
            "url": "classes/Html-AppWebPage.html"
        },                {
            "fqsen": "\\Html\\AppWebPage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-AppWebPage.html#method___construct"
        },                {
            "fqsen": "\\Html\\AppWebPage\u003A\u003AtoHtml\u0028\u0029",
            "name": "toHtml",
            "summary": "Permet\u0020de\u0020cr\u00E9er\u0020la\u0020page\u0020html\u0020adapter\u0020\u00E0\u0020l\u0027application",
            "url": "classes/Html-AppWebPage.html#method_toHtml"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm",
            "name": "TVShowForm",
            "summary": "",
            "url": "classes/Html-Form-TVShowForm.html"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-Form-TVShowForm.html#method___construct"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm\u003A\u003AgetTVShow\u0028\u0029",
            "name": "getTVShow",
            "summary": "",
            "url": "classes/Html-Form-TVShowForm.html#method_getTVShow"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm\u003A\u003AgetHtmlForm\u0028\u0029",
            "name": "getHtmlForm",
            "summary": "Permet\u0020de\u0020cr\u00E9er\u0020un\u0020formulaire\u0020pour\u0020une\u0020s\u00E9rie",
            "url": "classes/Html-Form-TVShowForm.html#method_getHtmlForm"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm\u003A\u003AsetEntityFromQueryString\u0028\u0029",
            "name": "setEntityFromQueryString",
            "summary": "Permet\u0020de\u0020cr\u00E9er\u0020une\u0020s\u00E9rie\u0020en\u0020r\u00E9cup\u00E9rant\u0020les\u0020informations\u0020d\u0027une\u0020query\u0020string",
            "url": "classes/Html-Form-TVShowForm.html#method_setEntityFromQueryString"
        },                {
            "fqsen": "\\Html\\Form\\TVShowForm\u003A\u003A\u0024show",
            "name": "show",
            "summary": "",
            "url": "classes/Html-Form-TVShowForm.html#property_show"
        },                {
            "fqsen": "\\Html\\StringEscaper",
            "name": "StringEscaper",
            "summary": "",
            "url": "classes/Html-StringEscaper.html"
        },                {
            "fqsen": "\\Html\\StringEscaper\u003A\u003AescapeString\u0028\u0029",
            "name": "escapeString",
            "summary": "Permet\u0020de\u0020se\u0020prot\u00E9ger\u0020les\u0020caract\u00E8res\u0020sp\u00E9ciaux\u0020pouvant\u0020d\u00E9grader\u0020la\u0020page\u0020Web.",
            "url": "classes/Html-StringEscaper.html#method_escapeString"
        },                {
            "fqsen": "\\Html\\StringEscaper\u003A\u003AstripTagsAndTrim\u0028\u0029",
            "name": "stripTagsAndTrim",
            "summary": "",
            "url": "classes/Html-StringEscaper.html#method_stripTagsAndTrim"
        },                {
            "fqsen": "\\Html\\WebPage",
            "name": "WebPage",
            "summary": "",
            "url": "classes/Html-WebPage.html"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-WebPage.html#method___construct"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetHead\u0028\u0029",
            "name": "getHead",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getHead"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getTitle"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_setTitle"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getBody"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetMenu\u0028\u0029",
            "name": "getMenu",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getMenu"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetHome\u0028\u0029",
            "name": "getHome",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getHome"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendToHead\u0028\u0029",
            "name": "appendToHead",
            "summary": "Permet\u0020d\u0027ajouter\u0020du\u0020contenu\u0020\u00E0\u0020la\u0020balise\u0020\u003Chead\u003E",
            "url": "classes/Html-WebPage.html#method_appendToHead"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendCss\u0028\u0029",
            "name": "appendCss",
            "summary": "Permet\u0020d\u0027ajouter\u0020du\u0020css\u0020\u00E0\u0020la\u0020page",
            "url": "classes/Html-WebPage.html#method_appendCss"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendCssUrl\u0028\u0029",
            "name": "appendCssUrl",
            "summary": "Permet\u0020d\u0027ajouter\u0020un\u0020lien\u0020vers\u0020une\u0020feuille\u0020de\u0020style\u0020css",
            "url": "classes/Html-WebPage.html#method_appendCssUrl"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendJs\u0028\u0029",
            "name": "appendJs",
            "summary": "Permet\u0020d\u0027ajouter\u0020du\u0020javascript\u0020\u00E0\u0020la\u0020page",
            "url": "classes/Html-WebPage.html#method_appendJs"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendJsUrl\u0028\u0029",
            "name": "appendJsUrl",
            "summary": "Permet\u0020d\u0027ajouter\u0020un\u0020lien\u0020vers\u0020un\u0020script\u0020JavaScript",
            "url": "classes/Html-WebPage.html#method_appendJsUrl"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendContent\u0028\u0029",
            "name": "appendContent",
            "summary": "Permet\u0020d\u0027ajouter\u0020du\u0020contenu\u0020\u00E0\u0020la\u0020balise\u0020\u003Cbody\u003E\u0020de\u0020la\u0020page",
            "url": "classes/Html-WebPage.html#method_appendContent"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AtoHTML\u0028\u0029",
            "name": "toHTML",
            "summary": "Permet\u0020de\u0020cr\u00E9er\u0020la\u0020page\u0020html",
            "url": "classes/Html-WebPage.html#method_toHTML"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetLastModification\u0028\u0029",
            "name": "getLastModification",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getLastModification"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendToMenu\u0028\u0029",
            "name": "appendToMenu",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendToMenu"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendMenuButton\u0028\u0029",
            "name": "appendMenuButton",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendMenuButton"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendHomeButton\u0028\u0029",
            "name": "appendHomeButton",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendHomeButton"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A\u0024head",
            "name": "head",
            "summary": "",
            "url": "classes/Html-WebPage.html#property_head"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A\u0024home",
            "name": "home",
            "summary": "",
            "url": "classes/Html-WebPage.html#property_home"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Html-WebPage.html#property_title"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/Html-WebPage.html#property_body"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A\u0024menu",
            "name": "menu",
            "summary": "",
            "url": "classes/Html-WebPage.html#property_menu"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Entity\\Collection",
            "name": "Collection",
            "summary": "",
            "url": "namespaces/entity-collection.html"
        },                {
            "fqsen": "\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/entity.html"
        },                {
            "fqsen": "\\Entity\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/entity-exception.html"
        },                {
            "fqsen": "\\Html",
            "name": "Html",
            "summary": "",
            "url": "namespaces/html.html"
        },                {
            "fqsen": "\\Html\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/html-form.html"
        }            ]
);
